---

- name: Set default solr server to point to CLAW core
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config-set search_api.server.default_solr_server backend_config.connector_config.core CLAW"
  register: set_search_api_config
  changed_when: "'Do you want to update' in set_search_api_config.stdout"

- name: Get solr config files to copy
  command: "find {{ webserver_document_root }}/drupal/web/modules/contrib/search_api_solr/solr-conf/7.x -type f"
  register: files_to_copy
  changed_when: false

- name: Copy solr config files
  copy:
    src: "{{ item }}"
    dest: "{{ solr_instance_conf_path }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    remote_src: True
  with_items:
    - "{{ files_to_copy.stdout_lines }}"

# https://www.drupal.org/project/search_api_solr/issues/3015993
- name: Set solr_install_path in solrcore.properties
  lineinfile:
    path: /var/solr/data/CLAW/conf/solrcore.properties
    regexp: '^solr\.install\.dir=.*$'
    line: solr.install.dir={{ solr_install_path }}
    state: present
  notify: restart solr
